### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by jfgodoy** [ryansolid/solid-scripts#1]
I figured out how to add environment variables to my project by adding a `.env` file in the root folder, but the variables require to start with `REACT_APP_`. was this overlooked?

**Comment by ryansolid** [comment]
Definitely thanks. If you know the place a PR would be welcome. Otherwise I will look into it in a couple days when I'm back from traveling.

**Comment by ryansolid** [comment]
Ok I've merged and published in v0.0.21.
