### ISSUE TITLE
upgrade to postcss 8

### ISSUE THREAD

**Issue by khuongduybui** [ryansolid/solid-scripts#15]
The instructions here (https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users) seem very straight-forward.

1.  Update `postcss-loader` to >= 4.0.3.
2.  Add `postcss` dependency to your project or update it to >= 8.1.

**Comment by khuongduybui** [comment]
After the update, I now have to manually patch this line https://github.com/ryansolid/solid-scripts/blob/master/config/webpack.config.js#L71 to `plugins: [...]` (instead of `plugins: () => [...]`).

**Comment by ryansolid** [comment]
To be clear removing the function call works as expected? Or is there more to be done here?

**Comment by khuongduybui** [comment]
All I did was removing the func call and it worked.
