### ISSUE TITLE
index.js file in dos format (?)

### ISSUE THREAD

**Issue by pipex** [ryansolid/solid-scripts#3]
I have a problem running the scripts after a yarn install on an app created with `npm init solid ts-app my-app` on OS X

When first created, the app runs without problem on `yarn start`, however if I delete the node_modules folder (to simulate a fresh repo clone) and run `yarn` to install packages I get 

```
yarn run v1.17.3
$ solid-scripts start
env: node\r: No such file or directory
error Command failed with exit code 127.
```

My guess was that for some reason the index.js in the `solid-scripts` module had the wrong line ending format, so I performed `dos2unix node_modules/solid-scripts/index.js`, and `yarn start` ran without issue.

What I don't understand is the different behavior when the app is freshly created than when yarn install is used.

**Comment by ryansolid** [comment]
Ok thanks I will look into it. I do dev on windows and I recently moved from WSL1 to WSL2 and I noticed when I moved stuff it messed with line endings.

**Comment by ryansolid** [comment]
Ok think I fixed it in v0.0.21.

**Comment by pipex** [comment]
It seems to be working. Thank you!

**Comment by ryansolid** [comment]
Awesome. Thanks for reporting.
