### ISSUE TITLE
DevDependencies inside Dependencies

### ISSUE THREAD

**Issue by sidharthv96** [ryansolid/solid-scripts#7]
Hi,
I created the typescript starter project and saw that things like typescript and @types are inside the dependencies inside package.json.
Is this by choice as solid is only supposed to generate the final files? I saw similar organisation inside this repo too.

I can create a PR to move stuff to devDependencies so that the project follows the universal standard. It will also allow people who are starting out with JS ecosystem to have a consistent feel.

**Comment by sidharthv96** [comment]
Should this be inside the create-solid repo?
Please close this if so.

**Comment by ryansolid** [comment]
Yeah I believe this is in the other repo and you already opened there so I will close this one and respond in the other issue.
